(function(){
"use strict";
const KEY="BS25_STATE";
const defaultState={coach:null,clients:[],session:null,settings:{version:"V25.1"}};
function load(){try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return {...defaultState}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function uid(){return "c_"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function layout(title,sub){return `<div class="shell"><div class="topbar"><div class="topbrand"><div class="bs-logo">BS</div><div><strong>BE STRONGER</strong><div class="muted">${sub||"V25.1"}</div></div></div><div class="top-actions"><a class="mini" href="index.html">Accueil</a><button class="mini" onclick="BS.logout()">Déconnexion</button></div></div><div class="nav" id="nav"></div><div id="content"></div></div>`}
function nav(items,active){return items.map(x=>`<button class="${x[0]===active?"active":""}" onclick="BS.go('${x[0]}')">${x[1]}</button>`).join("")}
function initCoach(){
 let s=load();
 if(!s.coach){return false}
 return true;
}
function renderCoach(){
 const s=load();
 if(!s.coach){document.getElementById("app").innerHTML=`<div class="shell login"><div class="card"><div class="bs-logo">BS</div><h1>Ton espace coach.</h1><p class="muted">Crée ton accès personnel. Aucun Supabase n'est nécessaire pour démarrer cette V25.1.</p><label>Email coach</label><input id="setupEmail" type="email" placeholder="ton@email.com"><label>Mot de passe</label><input id="setupPass" type="password" placeholder="Minimum 6 caractères"><button class="primary" onclick="BS.setupCoach()">CRÉER MON ACCÈS COACH</button><div id="msg"></div><p class="notice" style="margin-top:14px">Ce mode enregistre les comptes sur l'appareil/navigateur. Pour une synchronisation réelle entre plusieurs téléphones, il faudra connecter Supabase ensuite.</p></div></div>`;return}
 if(!s.session||s.session.role!=="coach"){renderCoachLogin();return}
 document.getElementById("app").innerHTML=layout("","ESPACE COACH");
 document.getElementById("nav").innerHTML=nav([["dashboard","Tableau"],["clients","Clients"],["program","Programmes"],["timer","Timer"]],location.hash.slice(1)||"dashboard");
 go(location.hash.slice(1)||"dashboard");
}
function renderCoachLogin(){
 document.getElementById("app").innerHTML=`<div class="shell login"><div class="card"><div class="bs-logo">BS</div><h1>Connexion coach.</h1><p class="muted">Accès réservé à ton espace coach.</p><label>Email</label><input id="loginEmail" type="email"><label>Mot de passe</label><input id="loginPass" type="password"><button class="primary" onclick="BS.loginCoach()">SE CONNECTER</button><div id="msg"></div><a class="mini" style="display:block;text-align:center;margin-top:12px" href="index.html">← Retour</a></div></div>`
}
function setupCoach(){const email=document.getElementById("setupEmail").value.trim().toLowerCase(),pass=document.getElementById("setupPass").value;if(!email||pass.length<6){document.getElementById("msg").innerHTML='<p class="error">Entre un email et un mot de passe d’au moins 6 caractères.</p>';return}let s=load();s.coach={email,pass};s.session={role:"coach"};save(s);location.reload()}
function loginCoach(){let s=load(),e=document.getElementById("loginEmail").value.trim().toLowerCase(),p=document.getElementById("loginPass").value;if(e===s.coach.email&&p===s.coach.pass){s.session={role:"coach"};save(s);location.reload()}else document.getElementById("msg").innerHTML='<p class="error">Email ou mot de passe incorrect.</p>'}
function logout(){let s=load();s.session=null;save(s);location.href="index.html"}
function go(view){if(!view)view="dashboard";location.hash=view;document.getElementById("nav").innerHTML=nav([["dashboard","Tableau"],["clients","Clients"],["program","Programmes"],["timer","Timer"]],view);({dashboard:dashboard,clients:clients,program:program,timer:timer}[view]||dashboard)()}
function dashboard(){let s=load(),active=s.clients.filter(c=>c.active!==false).length;document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><h2>Bonjour coach 👋</h2><p class="muted">Ton cockpit BE STRONGER.</p><div class="stat-grid"><div class="stat"><small>Clients</small><b>${s.clients.length}</b></div><div class="stat"><small>Actifs</small><b>${active}</b></div><div class="stat"><small>Programmes</small><b>${s.clients.filter(c=>c.program).length}</b></div><div class="stat"><small>Version</small><b>25.1</b></div></div></div><div class="card"><h2>Accès rapides</h2><button class="primary" onclick="BS.go('clients')">GÉRER MES CLIENTS</button><button class="secondary" style="width:100%;margin-top:8px" onclick="BS.go('program')">PROGRAMMES</button></div><div class="card"><h2>État de l'application</h2><div class="notice"><b>Mode local actif.</b><br>La page ne dépend plus de Supabase pour fonctionner. Tu peux créer ton accès coach et tes codes clients immédiatement.</div></div></div>`}
function clients(){let s=load();document.getElementById("content").innerHTML=`<div class="grid"><div class="card"><h2>Ajouter un client</h2><label>Nom / prénom</label><input id="newName" placeholder="Ex. Thomas"><div class="row"><div><label>Email (facultatif)</label><input id="newEmail" type="email"></div><div><label>Objectif</label><select id="newGoal"><option>Perte de gras</option><option>Hypertrophie</option><option>Performance</option><option>Remise en forme</option></select></div></div><button class="primary" onclick="BS.addClient()">CRÉER LE CLIENT</button><p id="clientMsg"></p><p class="notice">Un <b>code client unique</b> sera généré. Tu peux le communiquer au coaché.</p></div><div class="card"><h2>Mes clients <span class="muted">(${s.clients.length})</span></h2><div class="client-list">${s.clients.length?s.clients.map(c=>`<div class="client-row"><div class="client-info"><b>${esc(c.name)}</b><span>${esc(c.goal)} · Code ${esc(c.code)}</span></div><div><span class="badge">Actif</span><button class="mini" onclick="BS.openClient('${c.id}')">Ouvrir</button></div></div>`).join(""):'<div class="muted">Aucun client pour le moment.</div>'}</div></div></div>`}
function addClient(){let s=load(),name=document.getElementById("newName").value.trim();if(!name){document.getElementById("clientMsg").innerHTML='<span class="error">Indique le nom du client.</span>';return}let c={id:uid(),name,email:document.getElementById("newEmail").value.trim(),goal:document.getElementById("newGoal").value,code:code(),active:true,program:null,progress:[],created:new Date().toISOString()};s.clients.push(c);save(s);clients();openClient(c.id)}
function openClient(id){let s=load(),c=s.clients.find(x=>x.id===id);if(!c)return;document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><div class="top-actions"><button class="mini" onclick="BS.go('clients')">← Clients</button></div><h2>${esc(c.name)}</h2><p class="muted">${esc(c.goal)} · Code d'accès</p><div class="code">${esc(c.code)}</div><p class="notice">Communique uniquement ce code au client. Dans cette V25.1 locale, le code est enregistré sur cet appareil.</p></div><div class="card"><h2>Programme</h2><label>Nom du programme</label><input id="pName" value="${esc(c.program?.name||"Programme BE STRONGER")}"><label>Nombre de semaines</label><select id="pWeeks">${[4,6,8,12].map(n=>`<option ${c.program?.weeks===n?"selected":""}>${n}</option>`).join("")}</select><button class="primary" onclick="BS.saveProgram('${c.id}')">ENREGISTRER</button></div><div class="card"><h2>Accès client</h2><p class="muted">Le client voit uniquement son espace lorsqu'il se connecte avec son code.</p><button class="secondary" style="width:100%" onclick="BS.copy('${c.code}')">COPIER LE CODE</button></div></div>`}
function copy(t){navigator.clipboard?.writeText(t)}
function saveProgram(id){let s=load(),c=s.clients.find(x=>x.id===id);c.program={name:document.getElementById("pName").value,weeks:Number(document.getElementById("pWeeks").value),days:[{day:"Lundi",title:"Haut du corps",ex:[["Développé couché",4,8],["Rowing barre",4,10],["Élévations latérales",3,15]]},{day:"Jeudi",title:"Jambes",ex:[["Squat",4,8],["Fentes",3,10],["Gainage",3,60]]}]};save(s);openClient(id)}
function program(){let s=load();document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><h2>Programmes clients</h2>${s.clients.map(c=>`<div class="client-row"><div class="client-info"><b>${esc(c.name)}</b><span>${c.program?esc(c.program.name):"Aucun programme"}</span></div><button class="mini" onclick="BS.openClient('${c.id}')">GÉRER</button></div>`).join("")||'<p class="muted">Crée d’abord un client.</p>'}</div></div>`}
let timerState={sec:60,running:false,type:"AMRAP",int:null};
function timer(){document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><h2>Timer WOD</h2><div class="timer-type">${["AMRAP","EMOM","FOR TIME","TABATA"].map(t=>`<button id="tt-${t}" class="${timerState.type===t?"active":""}" onclick="BS.setTimerType('${t}')">${t}</button>`).join("")}</div><div class="timer-display" id="clock">${fmt(timerState.sec)}</div><div class="row"><div><label>Durée (secondes)</label><input id="timerSec" type="number" min="1" value="${timerState.sec}"></div><div><label>Exercice / consigne</label><input id="timerExercise" placeholder="Ex. 12 thrusters"></div></div><button class="primary" onclick="BS.startTimer()">DÉMARRER</button><button class="secondary" style="width:100%;margin-top:8px" onclick="BS.resetTimer()">RESET</button></div></div>`}
function fmt(n){n=Math.max(0,Math.round(n));return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")}
function setTimerType(t){timerState.type=t;timer()}
function startTimer(){if(timerState.running)return;timerState.sec=Number(document.getElementById("timerSec").value)||60;timerState.running=true;timerState.int=setInterval(()=>{timerState.sec--;let e=document.getElementById("clock");if(e)e.textContent=fmt(timerState.sec);if(timerState.sec<=0){clearInterval(timerState.int);timerState.running=false;navigator.vibrate?.([200,100,200]);alert("FIN");}},1000)}
function resetTimer(){clearInterval(timerState.int);timerState={sec:Number(document.getElementById("timerSec")?.value)||60,running:false,type:timerState.type,int:null};timer()}
function renderClient(){let s=load();if(!s.session||s.session.role!=="client"){clientLogin();return}let c=s.clients.find(x=>x.id===s.session.clientId);if(!c){s.session=null;save(s);clientLogin();return}document.getElementById("app").innerHTML=layout("","ESPACE CLIENT");document.getElementById("nav").innerHTML=nav([["home","Accueil"],["workout","Programme"],["progress","Progression"]],location.hash.slice(1)||"home");clientView(location.hash.slice(1)||"home",c)}
function clientLogin(){document.getElementById("app").innerHTML=`<div class="shell login"><div class="card"><div class="bs-logo">BS</div><h1>Espace client.</h1><p class="muted">Entre le code personnel donné par ton coach.</p><label>Code client</label><input id="clientCode" class="code" placeholder="ABC123" maxlength="8"><button class="primary" onclick="BS.loginClient()">ACCÉDER À MON ESPACE</button><div id="msg"></div><a class="mini" style="display:block;text-align:center;margin-top:12px" href="index.html">← Retour</a></div></div>`}
function loginClient(){let s=load(),codev=document.getElementById("clientCode").value.trim().toUpperCase(),c=s.clients.find(x=>x.code===codev);if(!c){document.getElementById("msg").innerHTML='<p class="error">Code client introuvable sur cet appareil.</p>';return}s.session={role:"client",clientId:c.id};save(s);location.reload()}
function clientView(view,c){document.getElementById("nav").innerHTML=nav([["home","Accueil"],["workout","Programme"],["progress","Progression"]],view);if(view==="workout")clientWorkout(c);else if(view==="progress")clientProgress(c);else clientHome(c)}
function clientHome(c){document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><h2>Bonjour ${esc(c.name)} 👋</h2><p class="muted">Bienvenue dans ton espace BE STRONGER.</p><div class="stat-grid"><div class="stat"><small>Objectif</small><b style="font-size:16px">${esc(c.goal)}</b></div><div class="stat"><small>Semaines</small><b>${c.program?.weeks||0}</b></div><div class="stat"><small>Séances</small><b>${c.program?.days?.length||0}</b></div><div class="stat"><small>Statut</small><b class="success">Actif</b></div></div></div><div class="card"><h2>Prochaine séance</h2><p>${c.program?.days?.[0]?.title||"Programme à venir"}</p><button class="primary" onclick="BS.goClient('workout')">COMMENCER</button></div><div class="card"><h2>Mon accès</h2><p class="muted">Code personnel</p><div class="code">${esc(c.code)}</div></div></div>`}
function clientWorkout(c){let days=c.program?.days||[];document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><h2>Mon programme</h2><div class="weeks">${Array.from({length:c.program?.weeks||4},(_,i)=>`<div class="week ${i===0?"active":""}">S${i+1}</div>`).join("")}</div></div>${days.map(d=>`<div class="card"><h2>${esc(d.day)} — ${esc(d.title)}</h2>${d.ex.map((e,i)=>`<div class="exercise"><div class="exercise-head"><b>${i+1}. ${esc(e[0])}</b><b>${e[1]} × ${e[2]}</b></div><div class="exercise-meta">Charge à renseigner · Reps réalisées · RPE</div><div class="charge-grid"><input placeholder="kg"><input placeholder="reps"><input placeholder="RPE"></div></div>`).join("")}<button class="primary">SÉANCE TERMINÉE</button></div>`).join("")||'<div class="card full"><p class="muted">Ton coach n’a pas encore publié de programme.</p></div>'}</div>`}
function clientProgress(c){document.getElementById("content").innerHTML=`<div class="grid"><div class="card full"><h2>Ma progression</h2><div class="stat-grid"><div class="stat"><small>Poids</small><b>—</b></div><div class="stat"><small>Séances</small><b>0</b></div><div class="stat"><small>Régularité</small><b>—</b></div><div class="stat"><small>Objectif</small><b style="font-size:14px">${esc(c.goal)}</b></div></div><p class="notice" style="margin-top:14px">Les données de progression seront enregistrées ici au fur et à mesure des séances.</p></div></div>`}
function goClient(view){location.hash=view;let s=load(),c=s.clients.find(x=>x.id===s.session.clientId);clientView(view,c)}
window.BS={renderCoach,renderClient,setupCoach,loginCoach,logout,go,addClient,openClient,saveProgram,copy,setTimerType,startTimer,resetTimer,loginClient,goClient};
window.addEventListener("hashchange",()=>{if(load().session?.role==="coach")go(location.hash.slice(1)||"dashboard");else if(load().session?.role==="client"){let s=load(),c=s.clients.find(x=>x.id===s.session.clientId);if(c)clientView(location.hash.slice(1)||"home",c)}});
})();